In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocab size

voc_size=10000


In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## One hot repwresentation


one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2304, 7461, 8104, 2775],
 [2304, 7461, 8104, 3003],
 [2304, 9765, 8104, 8816],
 [3014, 4301, 8006, 7090, 2066],
 [3014, 4301, 8006, 7090, 9982],
 [3325, 2304, 8995, 8104, 6934],
 [8806, 9637, 1445, 7090]]

In [8]:
## Word embadsing Reprresenation


from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 2304 7461 8104 2775]
 [   0    0    0    0 2304 7461 8104 3003]
 [   0    0    0    0 2304 9765 8104 8816]
 [   0    0    0 3014 4301 8006 7090 2066]
 [   0    0    0 3014 4301 8006 7090 9982]
 [   0    0    0 3325 2304 8995 8104 6934]
 [   0    0    0    0 8806 9637 1445 7090]]


In [11]:
## feature representation

dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

2025-05-27 16:36:14.689219: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 231ms/step


array([[[-2.95333024e-02,  1.86347477e-02,  1.32373236e-02,
         -2.84044817e-03, -3.99295464e-02,  4.66239937e-02,
          2.79386975e-02,  1.63513459e-02,  1.57032497e-02,
         -1.31048560e-02],
        [-2.95333024e-02,  1.86347477e-02,  1.32373236e-02,
         -2.84044817e-03, -3.99295464e-02,  4.66239937e-02,
          2.79386975e-02,  1.63513459e-02,  1.57032497e-02,
         -1.31048560e-02],
        [-2.95333024e-02,  1.86347477e-02,  1.32373236e-02,
         -2.84044817e-03, -3.99295464e-02,  4.66239937e-02,
          2.79386975e-02,  1.63513459e-02,  1.57032497e-02,
         -1.31048560e-02],
        [-2.95333024e-02,  1.86347477e-02,  1.32373236e-02,
         -2.84044817e-03, -3.99295464e-02,  4.66239937e-02,
          2.79386975e-02,  1.63513459e-02,  1.57032497e-02,
         -1.31048560e-02],
        [-4.03511524e-02, -4.72794659e-02,  1.08357668e-02,
         -3.65295038e-02, -2.62364987e-02, -2.64135245e-02,
         -3.28857191e-02,  3.59027423e-02,  4.606169

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 2304, 7461, 8104, 2775], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 133ms/step


array([[-0.0295333 ,  0.01863475,  0.01323732, -0.00284045, -0.03992955,
         0.04662399,  0.0279387 ,  0.01635135,  0.01570325, -0.01310486],
       [-0.0295333 ,  0.01863475,  0.01323732, -0.00284045, -0.03992955,
         0.04662399,  0.0279387 ,  0.01635135,  0.01570325, -0.01310486],
       [-0.0295333 ,  0.01863475,  0.01323732, -0.00284045, -0.03992955,
         0.04662399,  0.0279387 ,  0.01635135,  0.01570325, -0.01310486],
       [-0.0295333 ,  0.01863475,  0.01323732, -0.00284045, -0.03992955,
         0.04662399,  0.0279387 ,  0.01635135,  0.01570325, -0.01310486],
       [-0.04035115, -0.04727947,  0.01083577, -0.0365295 , -0.0262365 ,
        -0.02641352, -0.03288572,  0.03590274,  0.0460617 , -0.0243544 ],
       [-0.02893158, -0.04795105, -0.0138059 , -0.01751161,  0.0122376 ,
         0.01776805,  0.03572824,  0.04722821,  0.04663148, -0.00287044],
       [ 0.04687839, -0.01354011, -0.04943159,  0.00816386, -0.02734411,
        -0.03715318,  0.0279093 ,  0.01630897